CREATE TABLE "GCG_5244_DAILY_RCVR"(
 "BIRUNID" BIGINT,
 "PURCHASE_ORDER" CHAR(7),
 "PO_LINE" CHAR(3),
 "PART" CHAR(20),
 "LOCATION" CHAR(2),
 "QTY_RECEIVED" NUMERIC(12,4),
 "UM" CHAR(3),
 "DESCRIPTION" CHAR(30),
 "NAME_VENDOR" CHAR(30),
 "RECEIVER_TEXT" LONGVARCHAR,
 "RECEIVER_NO" CHAR(6),
 "DATE_RECEIVED" CHAR(10),
 "VENDOR" CHAR(6));
